-- 어흥해보카 TOEIC 초기 단어 데이터
-- CSV 컬럼 매핑: english -> english, meaning -> korean, level -> level, type -> type, example_sentence -> example
-- 현재 words 테이블에는 part, example_translation 컬럼이 없으므로 해당 CSV 컬럼은 삽입하지 않음.
-- level 값은 팀 공통 필터 기준에 맞춰 BASIC / FREQUENT / ADVANCED로 정규화함.

INSERT IGNORE INTO words (english, korean, level, type, example)
VALUES
('review', '검토하다', 'BASIC', 'LC', 'The manager will review the documents tomorrow.'),
('budget', '예산', 'BASIC', 'RC', 'The project was completed on time and within budget.'),
('candidate', '후보자', 'BASIC', 'LC', 'We are interviewing three candidates for the position.'),
('resume', '이력서', 'BASIC', 'LC', 'Please send your resume to the HR department.'),
('reservation', '예약', 'BASIC', 'LC', 'I would like to make a reservation for two people.'),
('delayed', '지연된', 'BASIC', 'LC', 'The flight has been delayed due to heavy rain.'),
('passenger', '승객', 'BASIC', 'LC', 'All passengers must fasten their seat belts.'),
('destination', '목적지', 'BASIC', 'LC', 'We will reach our destination in two hours.'),
('baggage', '수하물', 'BASIC', 'LC', 'Do not leave your baggage unattended.'),
('depart', '출발하다', 'BASIC', 'LC', 'The train will depart from platform three.'),
('benefit', '혜택', 'BASIC', 'RC', 'The new health plan offers many benefits.'),
('brief', '짧은', 'BASIC', 'LC', 'The meeting will be very brief.'),
('confirm', '확인하다', 'BASIC', 'LC', 'Please confirm your reservation by email.'),
('deadline', '마감일', 'BASIC', 'RC', 'The deadline for the report is Friday.'),
('description', '설명', 'BASIC', 'RC', 'Please read the job description carefully.'),
('document', '문서', 'BASIC', 'RC', 'Keep this document in a safe place.'),
('feedback', '피드백', 'BASIC', 'LC', 'We value feedback from our customers.'),
('invest', '투자하다', 'BASIC', 'RC', 'It is wise to invest in your education.'),
('opportunity', '기회', 'BASIC', 'RC', 'This is a great opportunity for growth.'),
('organize', '준비하다', 'BASIC', 'LC', 'She organized the annual conference.'),
('participate', '참여하다', 'BASIC', 'LC', 'Everyone is encouraged to participate.'),
('previous', '이전의', 'BASIC', 'RC', 'The previous owner kept the house well.'),
('attend', '참석하다', 'BASIC', 'LC', 'I have to attend a meeting at 3 PM.'),
('meeting', '회의', 'BASIC', 'LC', 'The meeting is scheduled for Monday.'),
('schedule', '일정', 'BASIC', 'LC', 'Please check your schedule for next week.'),
('office', '사무실', 'BASIC', 'LC', 'The office opens at 9 AM.'),
('employee', '직원', 'BASIC', 'RC', 'Every employee gets a discount.'),
('manager', '매니저', 'BASIC', 'RC', 'The manager approved the request.'),
('client', '고객', 'BASIC', 'LC', 'We have a meeting with a new client.'),
('customer', '손님', 'BASIC', 'RC', 'Customer satisfaction is our priority.'),
('product', '제품', 'BASIC', 'RC', 'This product is our best seller.'),
('service', '서비스', 'BASIC', 'LC', 'They offer excellent customer service.'),
('provide', '제공하다', 'BASIC', 'RC', 'We provide free delivery for all orders.'),
('require', '요구하다', 'BASIC', 'RC', 'This job requires a lot of experience.'),
('request', '요청하다', 'BASIC', 'RC', 'You can request a refund within 30 days.'),
('submit', '제출하다', 'BASIC', 'RC', 'Please submit your application online.'),
('receive', '받다', 'BASIC', 'LC', 'I received an email from the director.'),
('accept', '수락하다', 'BASIC', 'LC', 'We accept all major credit cards.'),
('send', '보내다', 'BASIC', 'LC', 'I will send you the details later.'),
('contact', '연락하다', 'BASIC', 'LC', 'Please contact us for more information.'),
('implement', '시행하다', 'FREQUENT', 'RC', 'The company plans to implement the new policy.'),
('revenue', '수익', 'FREQUENT', 'RC', 'Our quarterly revenue has increased.'),
('eligible', '자격이 있는', 'FREQUENT', 'RC', 'Only full-time employees are eligible.'),
('postpone', '연기하다', 'FREQUENT', 'LC', 'The meeting has been postponed.'),
('notify', '알리다', 'FREQUENT', 'LC', 'Please notify us immediately.'),
('temporary', '임시의', 'FREQUENT', 'RC', 'We are hiring a temporary assistant.'),
('forecast', '예측하다', 'FREQUENT', 'RC', 'Experts forecast a steady recovery.'),
('profitable', '수익성이 있는', 'FREQUENT', 'RC', 'The new product line is profitable.'),
('recruit', '채용하다', 'FREQUENT', 'LC', 'The university is recruiting professors.'),
('applicant', '지원자', 'FREQUENT', 'LC', 'Every applicant must submit a resume.'),
('evaluate', '평가하다', 'FREQUENT', 'LC', 'Performance is evaluated annually.'),
('promote', '승진시키다', 'FREQUENT', 'RC', 'She was promoted to marketing director.'),
('transfer', '전근하다', 'FREQUENT', 'LC', 'He requested a transfer to the branch.'),
('resign', '사임하다', 'FREQUENT', 'LC', 'The CEO decided to resign.'),
('board', '탑승하다', 'FREQUENT', 'LC', 'Passengers are boarding at gate five.'),
('transit', '환승', 'FREQUENT', 'LC', 'The goods were damaged in transit.'),
('agreement', '계약', 'FREQUENT', 'RC', 'Both parties signed the agreement.'),
('valid', '유효한', 'FREQUENT', 'RC', 'This ticket is valid for three days.'),
('expire', '만료되다', 'FREQUENT', 'RC', 'My passport will expire next month.'),
('strictly', '엄격하게', 'FREQUENT', 'RC', 'The rules are strictly enforced.'),
('terms', '조건', 'FREQUENT', 'RC', 'Read the terms and conditions carefully.'),
('negotiate', '협상하다', 'FREQUENT', 'RC', 'We need to negotiate a better deal.'),
('resolve', '해결하다', 'FREQUENT', 'RC', 'The management is trying to resolve it.'),
('violate', '위반하다', 'FREQUENT', 'RC', 'Do not violate the safety regulations.'),
('verify', '확인하다', 'FREQUENT', 'RC', 'Please verify your account online.'),
('alternative', '대안', 'FREQUENT', 'RC', 'We are considering several alternatives.'),
('analyze', '분석하다', 'FREQUENT', 'RC', 'Experts are analyzing the market trends.'),
('anticipate', '예상하다', 'FREQUENT', 'RC', 'We anticipate a high demand.'),
('appoint', '임명하다', 'FREQUENT', 'RC', 'The board appointed a new chairman.'),
('assemble', '조립하다', 'FREQUENT', 'RC', 'The workers assembled the components.'),
('assign', '할당하다', 'FREQUENT', 'RC', 'The manager assigned a new task.'),
('assume', '맡다', 'FREQUENT', 'RC', 'She will assume the role of manager.'),
('authorize', '권한을 부여하다', 'FREQUENT', 'RC', 'Only authorized personnel can enter.'),
('campaign', '캠페인', 'FREQUENT', 'RC', 'The election campaign was successful.'),
('collaborate', '협력하다', 'FREQUENT', 'RC', 'The two departments collaborated.'),
('consult', '상담하다', 'FREQUENT', 'RC', 'You should consult a lawyer.'),
('contribute', '기여하다', 'FREQUENT', 'RC', 'Every employee contributed.'),
('convince', '설득하다', 'FREQUENT', 'RC', 'He tried to convince the client.'),
('decline', '거절하다', 'FREQUENT', 'RC', 'Profits declined significantly.'),
('demonstrate', '입증하다', 'FREQUENT', 'LC', 'The salesperson demonstrated it.'),
('accommodate', '수용하다', 'ADVANCED', 'LC', 'The hotel can accommodate 500 guests.'),
('mandatory', '의무적인', 'ADVANCED', 'RC', 'Attendance is mandatory.'),
('substantial', '상당한', 'ADVANCED', 'RC', 'We noticed a substantial improvement.'),
('expenditure', '지출', 'ADVANCED', 'RC', 'We need to reduce our expenditure.'),
('reimburse', '상환하다', 'ADVANCED', 'RC', 'The company will reimburse your expenses.'),
('audit', '회계 감사', 'ADVANCED', 'RC', 'An independent firm will conduct the audit.'),
('deficit', '적자', 'ADVANCED', 'RC', 'The government is trying to reduce the deficit.'),
('surplus', '흑자', 'ADVANCED', 'RC', 'The factory produced a surplus.'),
('compensation', '보상', 'ADVANCED', 'RC', 'The job offers excellent compensation.'),
('terminate', '끝나다', 'ADVANCED', 'RC', 'The contract will terminate in December.'),
('itinerary', '여행 일정표', 'ADVANCED', 'LC', 'The agent sent me the itinerary.'),
('complimentary', '무료의', 'ADVANCED', 'LC', 'The hotel provides a complimentary breakfast.'),
('binding', '법적 구속력이 있는', 'ADVANCED', 'RC', 'This is a legally binding contract.'),
('compliant', '규정을 준수하는', 'ADVANCED', 'RC', 'The software is fully compliant.'),
('acquire', '인수하다', 'ADVANCED', 'RC', 'The firm is looking to acquire a competitor.'),
('allocate', '할당하다', 'ADVANCED', 'RC', 'Funds were allocated for the campaign.'),
('amend', '수정하다', 'ADVANCED', 'RC', 'The contract was amended.'),
('commodity', '상품', 'ADVANCED', 'RC', 'Oil is a vital global commodity.'),
('endorse', '지지하다', 'ADVANCED', 'RC', 'The celebrity endorsed the new perfume.'),
('fluctuate', '변동하다', 'ADVANCED', 'RC', 'Stock prices fluctuate daily.'),
('comprehensive', '포괄적인', 'ADVANCED', 'RC', 'We offer comprehensive insurance.'),
('stringent', '엄격한', 'ADVANCED', 'RC', 'They follow stringent safety rules.'),
('lucrative', '수익성이 좋은', 'ADVANCED', 'RC', 'He was offered a lucrative contract.'),
('tentative', '잠정적인', 'ADVANCED', 'RC', 'We made a tentative agreement.'),
('unanimous', '만장일치의', 'ADVANCED', 'RC', 'The board reached a unanimous decision.'),
('consecutive', '연속적인', 'ADVANCED', 'RC', 'Sales fell for three consecutive months.'),
('alleviate', '완화하다', 'ADVANCED', 'RC', 'The new road will alleviate traffic.'),
('counterpart', '상대방', 'ADVANCED', 'RC', 'He met with his French counterpart.'),
('versatile', '다재다능한', 'ADVANCED', 'RC', 'This tool is highly versatile.'),
('obsolete', '구식의', 'ADVANCED', 'RC', 'Typewriters are now obsolete.'),
('unprecedented', '전례 없는', 'ADVANCED', 'RC', 'The company saw unprecedented growth.'),
('discrepancy', '불일치', 'ADVANCED', 'RC', 'There is a discrepancy in the accounts.'),
('proficient', '능숙한', 'ADVANCED', 'RC', 'She is proficient in multiple languages.'),
('prerequisite', '전제 조건', 'ADVANCED', 'RC', 'A degree is a prerequisite for this job.'),
('pertain', '관련되다', 'ADVANCED', 'RC', 'The laws pertain to environmental protection.'),
('subsidize', '보조금을 주다', 'ADVANCED', 'RC', 'The government subsidizes agriculture.'),
('meticulously', '꼼꼼하게', 'ADVANCED', 'RC', 'The event was meticulously planned.'),
('inadvertently', '무심코', 'ADVANCED', 'RC', 'He inadvertently deleted the file.'),
('viable', '실행 가능한', 'ADVANCED', 'RC', 'Is there any commercially viable option?'),
('deliberate', '고의적인', 'ADVANCED', 'RC', 'It was a deliberate attempt to hide facts.');
